name: ci
on: [push]

env:
  # installing the cypress binary takes really long, this disables that
  CYPRESS_INSTALL_BINARY: 0
  # the prisma postinstall fails with pnpm
  PRISMA_SKIP_POSTINSTALL_GENERATE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # need the cypress binary during cypress tests,
      # unsetting this variable will cause the binary to be installed
      CYPRESS_INSTALL_BINARY: ""
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/setup
      - run: pnpm run db-start
      - run: pnpm run test
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test artifacts
          path: cypress/videos/*

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/setup
      - run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/setup
      - run: pnpm run typecheck

  deploy:
    needs: [test, lint, typecheck]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
